<?php
# Copyright (c) 2017, Infomaniak Network SA.
# Copyright (c) 2019, Ideative Sàrl
# All rights reserved.

namespace Infomaniak;

use GuzzleHttp\Command\Guzzle\GuzzleClient;

/**
 * This is a pseudo class rendering to allow the use of PHPDoc comments
 * autogenerated in IDE as API methods are called dynamically using Guzzle
 */

if (class_exists('\Infomaniak\PHPDocForIDE')) {
    class MiddleManForIDE extends PHPDocForIDE { }
} else {
    class MiddleManForIDE extends GuzzleClient { }
}